version: '3'
services:
  website:
    build: ./
    image: website:0.1
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/website'
      SPRING_DATASOURCE_USERNAME: 'website'
      SPRING_DATASOURCE_PASSWORD: 'website'
    ports:
     - 8080:8080
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: 'website'
      POSTGRES_USER: 'website'
      POSTGRES_PASSWORD: 'website'
