spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/database
    username: username
    password: password
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: 'true'
